import 'package:hive/hive.dart';

/// Simple Student model stored in Hive.
///
/// The TypeAdapter below is written by hand (rather than generated by
/// build_runner) so this project runs with zero code-gen steps — just
/// `flutter pub get` and go.
class Student extends HiveObject {
  String name;
  String course;
  int age;

  Student({required this.name, required this.course, required this.age});
}

class StudentAdapter extends TypeAdapter<Student> {
  @override
  final int typeId = 0;

  @override
  Student read(BinaryReader reader) {
    final numOfFields = reader.readByte();
    final fields = <int, dynamic>{
      for (int i = 0; i < numOfFields; i++) reader.readByte(): reader.read(),
    };
    return Student(
      name: fields[0] as String,
      course: fields[1] as String,
      age: fields[2] as int,
    );
  }

  @override
  void write(BinaryWriter writer, Student obj) {
    writer
      ..writeByte(3)
      ..writeByte(0)
      ..write(obj.name)
      ..writeByte(1)
      ..write(obj.course)
      ..writeByte(2)
      ..write(obj.age);
  }
}
